-- Generated entity-geometry catalog consumed by shared descriptors and the
-- authoritative runtime. It maps each supported entity orientation to relative
-- rail nodes and turnout interaction positions.
-- Generated by tilesets/build_geometry.py. Do not edit by hand.
RailroaderWaymanEntityGeometry = {
    Left45DegTurn = {
        N = { nodes = { { x = 1, y = 1, z = 0 } }, kind = "turn" },
        S = { nodes = { { x = 5, y = 2, z = 0 } }, kind = "turn" },
        E = { nodes = { { x = 4, y = 1, z = 0 } }, kind = "turn" },
        W = { nodes = { { x = 1, y = 1, z = 0 } }, kind = "turn" },
    },
    Right45DegTurn = {
        N = { nodes = { { x = 4, y = 1, z = 0 } }, kind = "turn" },
        S = { nodes = { { x = 1, y = 1, z = 0 } }, kind = "turn" },
        E = { nodes = { { x = 3, y = 2, z = 0 } }, kind = "turn" },
        W = { nodes = { { x = 1, y = 1, z = 0 } }, kind = "turn" },
    },
    Right45DegTurnoutDiag = {
        N = { at = { x = 4, y = 2, z = 0 }, switch = { x = 2, y = 4, z = 0 }, divergingNodes = { { x = 4, y = 6, z = 0 } }, kind = "turnout" },
        S = { at = { x = 1, y = 4, z = 0 }, switch = { x = 3, y = 3, z = 0 }, divergingNodes = { { x = 1, y = -1, z = 0 } }, kind = "turnout" },
        W = { at = { x = 4, y = 2, z = 0 }, switch = { x = 6, y = 4, z = 0 }, divergingNodes = { { x = 9, y = 2, z = 0 } }, kind = "turnout" },
    },
    WyeTurnout = {
        S = { at = { x = 5, y = 3, z = 0 }, switch = { x = 3, y = 4, z = 0 }, divergingNodes = { { x = 1, y = -1, z = 0 } }, throughNodes = { { x = 9, y = -1, z = 0 } }, kind = "turnout" },
    },
    Right45DegTurnout = {
        N = { at = { x = 6, y = 2, z = 0 }, switch = { x = 4, y = 0, z = 0 }, divergingNodes = { { x = 2, y = 6, z = 0 } }, kind = "turnout" },
        E = { at = { x = 3, y = 2, z = 0 }, switch = { x = 4, y = 0, z = 0 }, divergingNodes = { { x = 0, y = -1, z = 0 } }, kind = "turnout" },
        S = { at = { x = 2, y = 4, z = 0 }, switch = { x = 0, y = 5, z = 0 }, divergingNodes = { { x = 7, y = -1, z = 0 } }, kind = "turnout" },
        W = { at = { x = 1, y = 1, z = 0 }, switch = { x = 0, y = 3, z = 0 }, divergingNodes = { { x = 4, y = 4, z = 0 } }, kind = "turnout" },
    },
    Left45DegTurnout = {
        N = { at = { x = 2, y = 2, z = 0 }, switch = { x = 0, y = 0, z = 0 }, divergingNodes = { { x = 6, y = 6, z = 0 } }, kind = "turnout" },
        S = { at = { x = 6, y = 4, z = 0 }, switch = { x = 4, y = 5, z = 0 }, divergingNodes = { { x = 1, y = -1, z = 0 } }, kind = "turnout" },
        E = { at = { x = 4, y = 2, z = 0 }, switch = { x = 6, y = 0, z = 0 }, divergingNodes = { { x = 2, y = 4, z = 0 } }, kind = "turnout" },
        W = { at = { x = 3, y = 2, z = 0 }, switch = { x = 0, y = 0, z = 0 }, divergingNodes = { { x = 6, y = -1, z = 0 } }, kind = "turnout" },
    },
    Left90DegTurnout = {
        N = { at = { x = 2, y = 4, z = 0 }, switch = { x = 0, y = 0, z = 0 }, divergingNodes = { { x = 5, y = 4, z = 0 } }, kind = "turnout" },
    },
    Left45DegTurnoutDiag = {
        N = { at = { x = 4, y = 2, z = 0 }, switch = { x = 5, y = 0, z = 0 }, divergingNodes = { { x = 1, y = -1, z = 0 } }, kind = "turnout" },
        W = { at = { x = 4, y = 4, z = 0 }, switch = { x = 2, y = 1, z = 0 }, divergingNodes = { { x = 4, y = -1, z = 0 } }, kind = "turnout" },
    },
}
